import { auth } from "@clerk/nextjs/server";
import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

export async function POST(req: Request) {
  try {
    const { userId } = await auth();
    if (!userId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const user = await prisma.user.findUnique({ where: { clerkId: userId } });
    if (!user) return NextResponse.json({ error: "User not found" }, { status: 404 });

    const { applicationId, title } = await req.json();
    if (!applicationId || !title) return NextResponse.json({ error: "Missing fields" }, { status: 400 });

    // Verify ownership
    const app = await prisma.application.findFirst({ where: { id: applicationId, userId: user.id } });
    if (!app) return NextResponse.json({ error: "Not found" }, { status: 404 });

    const task = await prisma.task.create({ data: { applicationId, title, isAutoGenerated: false } });
    return NextResponse.json(task, { status: 201 });
  } catch (error) {
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}
