export type Plan = "FREE" | "PRO";

export type ApplicationStatus =
  | "NOT_STARTED"
  | "IN_PROGRESS"
  | "SUBMITTED"
  | "INTERVIEW"
  | "ACCEPTED"
  | "REJECTED"
  | "WITHDRAWN";

export type DocumentType = "SOP" | "CV" | "TRANSCRIPT" | "OTHER";
export type ReviewType = "SOP" | "CV";
export type DegreeType = "MASTERS" | "PHD" | "BOTH";
export type ProcessStage =
  | "JUST_STARTING"
  | "RESEARCHING"
  | "IN_PROGRESS"
  | "ALMOST_DONE";

export type NotificationType =
  | "DEADLINE_REMINDER"
  | "TASK_OVERDUE"
  | "AI_LIMIT_REACHED"
  | "SUBSCRIPTION_EVENT"
  | "GENERAL";

export interface User {
  id: string;
  clerkId: string;
  email: string;
  name?: string | null;
  plan: Plan;
  subscriptionStatus?: string | null;
  trialEndsAt?: Date | null;
  planExpiresAt?: Date | null;
  onboardingCompleted: boolean;
  intakeCycle?: string | null;
  degreeType?: DegreeType | null;
  schoolCountRange?: string | null;
  regions: string[];
  processStage?: ProcessStage | null;
  aiReviewsToday: number;
  aiReviewsResetAt?: Date | null;
  createdAt: Date;
}

export interface Application {
  id: string;
  userId: string;
  universityName: string;
  program: string;
  country: string;
  deadline: Date;
  status: ApplicationStatus;
  createdAt: Date;
  tasks?: Task[];
  documents?: Document[];
}

export interface Task {
  id: string;
  applicationId: string;
  title: string;
  completed: boolean;
  isAutoGenerated: boolean;
  createdAt: Date;
}

export interface Document {
  id: string;
  applicationId?: string | null;
  userId: string;
  type: DocumentType;
  fileUrl: string;
  fileName: string;
  fileSize?: number | null;
  createdAt: Date;
}

export interface DocumentReview {
  id: string;
  userId: string;
  documentId: string;
  type: ReviewType;
  clarityScore: number;
  strengthScore: number;
  suggestions: string[];
  highlight: string;
  createdAt: Date;
}

export interface Payment {
  id: string;
  userId: string;
  amount: number;
  currency: string;
  status: "PENDING" | "SUCCESS" | "FAILED";
  transactionReference: string;
  createdAt: Date;
}

export interface Notification {
  id: string;
  userId: string;
  type: NotificationType;
  title: string;
  message: string;
  read: boolean;
  createdAt: Date;
}

export type ApplicationStatusConfig = {
  label: string;
  color: string;
  bg: string;
};
