export type Plan = "FREE" | "PRO";

export type ApplicationStatus =
  | "NOT_STARTED"
  | "IN_PROGRESS"
  | "SUBMITTED"
  | "INTERVIEW"
  | "ACCEPTED"
  | "REJECTED"
  | "WITHDRAWN";

export type DocumentType = "SOP" | "CV" | "TRANSCRIPT" | "OTHER";
export type ReviewType = "SOP" | "CV";
export type DegreeType = "MASTERS" | "PHD" | "BOTH";
export type ProcessStage =
  | "JUST_STARTING"
  | "RESEARCHING"
  | "IN_PROGRESS"
  | "ALMOST_DONE";

export type NotificationType =
  | "DEADLINE_REMINDER"
  | "TASK_OVERDUE"
  | "AI_LIMIT_REACHED"
  | "SUBSCRIPTION_EVENT"
  | "GENERAL";

export interface User {
  id: string;
  clerkId: string;
  email: string;
  name?: string;
  plan: Plan;
  subscriptionStatus?: string;
  trialEndsAt?: Date;
  planExpiresAt?: Date;
  onboardingCompleted: boolean;
  intakeCycle?: string;
  degreeType?: DegreeType;
  schoolCountRange?: string;
  regions: string[];
  processStage?: ProcessStage;
  aiReviewsToday: number;
  aiReviewsResetAt?: Date;
  createdAt: Date;
}

export interface Application {
  id: string;
  userId: string;
  universityName: string;
  program: string;
  country: string;
  deadline: Date;
  status: ApplicationStatus;
  createdAt: Date;
  tasks?: Task[];
  documents?: Document[];
}

export interface Task {
  id: string;
  applicationId: string;
  title: string;
  completed: boolean;
  isAutoGenerated: boolean;
  createdAt: Date;
}

export interface Document {
  id: string;
  applicationId?: string;
  userId: string;
  type: DocumentType;
  fileUrl: string;
  fileName: string;
  fileSize?: number;
  createdAt: Date;
}

export interface DocumentReview {
  id: string;
  userId: string;
  documentId: string;
  type: ReviewType;
  clarityScore: number;
  strengthScore: number;
  suggestions: string[];
  highlight: string;
  createdAt: Date;
}

export interface Payment {
  id: string;
  userId: string;
  amount: number;
  currency: string;
  status: "PENDING" | "SUCCESS" | "FAILED";
  transactionReference: string;
  createdAt: Date;
}

export interface Notification {
  id: string;
  userId: string;
  type: NotificationType;
  title: string;
  message: string;
  read: boolean;
  createdAt: Date;
}

export type ApplicationStatusConfig = {
  label: string;
  color: string;
  bg: string;
};

export const APPLICATION_STATUS_CONFIG: Record<
  ApplicationStatus,
  ApplicationStatusConfig
> = {
  NOT_STARTED: { label: "Not Started", color: "text-gray-600", bg: "bg-gray-100" },
  IN_PROGRESS: { label: "In Progress", color: "text-blue-600", bg: "bg-blue-100" },
  SUBMITTED: { label: "Submitted", color: "text-purple-600", bg: "bg-purple-100" },
  INTERVIEW: { label: "Interview", color: "text-amber-600", bg: "bg-amber-100" },
  ACCEPTED: { label: "Accepted", color: "text-green-600", bg: "bg-green-100" },
  REJECTED: { label: "Rejected", color: "text-red-600", bg: "bg-red-100" },
  WITHDRAWN: { label: "Withdrawn", color: "text-gray-500", bg: "bg-gray-50" },
};
