import { auth } from "@clerk/nextjs/server";
import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { AUTO_GENERATED_TASKS, FREE_PLAN_LIMITS } from "@/lib/utils";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function GET() {
  try {
    const { userId } = await auth();
    if (!userId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    const user = await prisma.user.findUnique({ where: { clerkId: userId } });
    if (!user) return NextResponse.json({ error: "User not found" }, { status: 404 });
    const applications = await prisma.application.findMany({
      where: { userId: user.id },
      include: { tasks: { orderBy: { createdAt: "asc" } }, documents: true },
      orderBy: { deadline: "asc" },
    });
    return NextResponse.json(applications);
  } catch (error) {
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}

export async function POST(req: Request) {
  try {
    const { userId } = await auth();
    if (!userId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    const user = await prisma.user.findUnique({ where: { clerkId: userId } });
    if (!user) return NextResponse.json({ error: "User not found" }, { status: 404 });
    if (user.plan === "FREE") {
      const count = await prisma.application.count({ where: { userId: user.id } });
      if (count >= FREE_PLAN_LIMITS.applications) {
        return NextResponse.json({ error: "FREE_LIMIT_REACHED", message: "Upgrade to Pro for unlimited applications" }, { status: 403 });
      }
    }
    const body = await req.json();
    const { universityName, program, country, deadline } = body;
    if (!universityName || !program || !country || !deadline) {
      return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
    }
    const existing = await prisma.application.findFirst({ where: { userId: user.id, universityName, program } });
    if (existing) {
      return NextResponse.json({ error: "DUPLICATE", message: "You already have this application" }, { status: 409 });
    }
    const application = await prisma.application.create({
      data: { userId: user.id, universityName, program, country, deadline: new Date(deadline), status: "NOT_STARTED" },
    });
    await prisma.task.createMany({
      data: AUTO_GENERATED_TASKS.map((title) => ({ applicationId: application.id, title, isAutoGenerated: true })),
    });
    const appWithTasks = await prisma.application.findUnique({ where: { id: application.id }, include: { tasks: true } });
    return NextResponse.json(appWithTasks, { status: 201 });
  } catch (error) {
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}
