import { auth, currentUser } from "@clerk/nextjs/server";
import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { AUTO_GENERATED_TASKS } from "@/lib/utils";

export async function POST(req: Request) {
  try {
    const { userId } = await auth();
    if (!userId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const clerkUser = await currentUser();
    const body = await req.json();
    const { name, schoolCountRange, intakeCycle, degreeType, regions, processStage, firstApplication } = body;

    // Upsert user
    const user = await prisma.user.upsert({
      where: { clerkId: userId },
      update: {
        name: name || clerkUser?.firstName || "",
        schoolCountRange,
        intakeCycle,
        degreeType,
        regions: regions || [],
        processStage,
        onboardingCompleted: true,
      },
      create: {
        clerkId: userId,
        email: clerkUser?.emailAddresses[0]?.emailAddress || "",
        name: name || clerkUser?.firstName || "",
        schoolCountRange,
        intakeCycle,
        degreeType,
        regions: regions || [],
        processStage,
        onboardingCompleted: true,
      },
    });

    // Create first application + auto-tasks if provided
    if (firstApplication?.universityName && firstApplication?.program && firstApplication?.deadline) {
      const app = await prisma.application.create({
        data: {
          userId: user.id,
          universityName: firstApplication.universityName,
          program: firstApplication.program,
          country: "Unknown",
          deadline: new Date(firstApplication.deadline),
          status: "NOT_STARTED",
        },
      });

      await prisma.task.createMany({
        data: AUTO_GENERATED_TASKS.map((title) => ({
          applicationId: app.id,
          title,
          isAutoGenerated: true,
        })),
      });
    }

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error("Onboarding error:", error);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}
