import { auth, currentUser } from "@clerk/nextjs/server";
import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { AUTO_GENERATED_TASKS } from "@/lib/utils";
import { DegreeType, ProcessStage } from "@prisma/client";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

// Collapse the wizard's multi-select degree array into the single DegreeType enum.
function toDegreeType(input: unknown): DegreeType | null {
  const arr = Array.isArray(input) ? input.map(String) : input ? [String(input)] : [];
  const hasMasters = arr.includes("MASTERS");
  const hasPhd = arr.includes("PHD");
  if (hasMasters && hasPhd) return DegreeType.BOTH;
  if (hasMasters) return DegreeType.MASTERS;
  if (hasPhd) return DegreeType.PHD;
  return null; // MBA / OTHER / none — not representable in the current enum
}

function toProcessStage(input: unknown): ProcessStage | null {
  const v = typeof input === "string" ? input : "";
  return (Object.values(ProcessStage) as string[]).includes(v)
    ? (v as ProcessStage)
    : null;
}

export async function POST(req: Request) {
  try {
    const { userId } = await auth();
    if (!userId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    const clerkUser = await currentUser();
    const body = await req.json();
    const {
      name,
      degreeType,
      intakeCycle,
      regions,
      schoolCountRange,
      processStage,
      firstApplication,
    } = body;

    // Map onboarding answers to the actual User schema.
    // Note: "field of study" is collected in the wizard but not persisted (no column yet).
    const onboardingData = {
      name: name || clerkUser?.firstName || "",
      degreeType: toDegreeType(degreeType),
      intakeCycle: typeof intakeCycle === "string" && intakeCycle ? intakeCycle : null,
      regions: Array.isArray(regions) ? regions.map(String) : [],
      schoolCountRange:
        typeof schoolCountRange === "string" && schoolCountRange ? schoolCountRange : null,
      processStage: toProcessStage(processStage),
      onboardingCompleted: true,
    };

    const user = await prisma.user.upsert({
      where: { clerkId: userId },
      update: onboardingData,
      create: {
        clerkId: userId,
        email: clerkUser?.emailAddresses[0]?.emailAddress || "",
        ...onboardingData,
      },
    });

    if (
      firstApplication?.universityName &&
      firstApplication?.program &&
      firstApplication?.deadline
    ) {
      const app = await prisma.application.create({
        data: {
          userId: user.id,
          universityName: firstApplication.universityName,
          program: firstApplication.program,
          country: firstApplication.country || "Unknown",
          deadline: new Date(firstApplication.deadline),
          status: "NOT_STARTED",
        },
      });
      await prisma.task.createMany({
        data: AUTO_GENERATED_TASKS.map((title) => ({
          applicationId: app.id,
          title,
          isAutoGenerated: true,
        })),
      });
    }

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error("Onboarding error:", error);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}

